name: tests

on:
  - push
  - pull_request

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: ['7.3', '7.4', '8.0']
        stability: [prefer-stable]
        include:
          - php: '8.1'
            stability: prefer-stable

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          tools: composer:v2
          coverage: none

      - name: Mimic PHP 8.0
        run: composer config platform.php 8.0.999
        if: matrix.php > 8

      - name: Install dependencies
        uses: nick-invision/retry@v1
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute tests
        continue-on-error: ${{ matrix.php > 8 }}
        run: vendor/bin/phpunit --verbose
